version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-main
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: id.tickell.us
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_PROXY_HEADERS: "xforwarded"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    command: ["start", "--truststore-paths=/opt/keycloak/conf/truststores/tickell-us-ca.crt"]
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./config/keycloak:/opt/keycloak/conf:z
    networks:
      - keycloak-net
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro,z
      - ./certs/id.tickell.us.crt:/etc/ssl/certs/id.tickell.us.crt:ro,z
      - ./certs/id.tickell.us.key:/etc/ssl/private/id.tickell.us.key:ro,z
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - keycloak-net
    restart: unless-stopped

volumes:
  postgres-data:
  keycloak-data:
  caddy-data:
  caddy-config:

networks:
  keycloak-net:
    driver: bridge