version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-main
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: id.tickell.us
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_PROXY_HEADERS: "xforwarded"
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_FEATURES: "${KC_FEATURES}"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      JAVA_OPTS: "-Djava.security.krb5.conf=/opt/keycloak/conf/krb5.conf"
    command: ["start", "--truststore-paths=/opt/keycloak/conf/truststores/tickell-us-ca.crt"]
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./config/keycloak:/opt/keycloak/conf:z
    networks:
      - keycloak-net
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro,z
      - ./certs/id.tickell.us.crt:/etc/ssl/certs/id.tickell.us.crt:ro,z
      - ./certs/id.tickell.us.key:/etc/ssl/private/id.tickell.us.key:ro,z
      - ../caddy-logs:/data
      - caddy-config:/config
    networks:
      - keycloak-net
    restart: unless-stopped

  vaultwarden:
    image: docker.io/vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.tickell.us"
      #SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "${VW_ADMIN_TOKEN}"
      ROCKET_PORT: 8082
      SSO_ENABLED: "true"
      SSO_AUTHORITY: "https://id.tickell.us/realms/tickell"
      SSO_CLIENT_ID: "vaultwarden"
      SSO_CLIENT_SECRET: "${VW_CLIENT_SECRET}"
      SSO_SCOPES: "openid email profile"
      SSO_DISPLAY_NAME: "Family SSO"
      SSO_ONLY: "false"
      LOG_LEVEL: "${VW_LOG_LEVEL}"
    expose:
      - "8082"
    volumes:
      - vaultwarden-data:/data
      - ./certs/tickell-us-ca.crt:/usr/local/share/ca-certificates/tickell-us-ca.crt:ro
    command: ["sh", "-c", "update-ca-certificates && /vaultwarden"]
    networks:
      - keycloak-net

volumes:
  postgres-data:
  keycloak-data:
  caddy-data:
  caddy-config:
  vaultwarden-data:

networks:
  keycloak-net:
    driver: bridge